=pod

README for package 'mootm'

Last updated for mootm version 2.0.1

=head1 DESCRIPTION

mootm - moocow's part-of-speech tagger: morphology.

=head1 REQUIREMENTS

=over 4


=item moot E<gt>= v2.0.0

Available from http://www.ling.uni-potsdam.de/~moocw/projects/moot


=item Underlying finite-state device library

mootm can use any one of several underlying libraries
for finite-state device operations, including the following:

=over 4

=item GNU libgfsm E<gt>= v0.0.7

Available from http://www.ling.uni-potsdam.de/~moocow/projects/gfsm

=item University of Potsdam FSMlib E<gt> v0.9.0.1

For details and availability, contact its author, Thomas Hanneforth.

=item RWTH libFsa

Available from http://www.informatik.rwth-aachen.de/I6/~kanthak/fsa.html

RWTH libFsa support is implemented but currently broken.
Feel free to fix it if you like.

=back


=item pkg-config

Available from:
http://www.freedesktop.org/software/pkgconfig/


=item flex++ , bison++

Alain Coetmeur's C++ ports of the famous lexer/parser
generator pair, available from:
ftp://iecc.com/pub/file/bison++flex++
or
from the official distribution site of this package.

Tested with flex++-v2.3.8-4 and bison++-v1.21-5.


=item Perl (Optional)

Get it from http://www.cpan.org or http://www.perl.com
Required for building command-line parsers, utility
documentation, library documentation, etc.

=item Getopt::Gen

A Perl module used to generate command-line option parsers.
Available from:
http://www.ling.uni-potsdam.de/~moocow/projects/perl/index.html#gog

=item pod2man, pod2text, pod2html (Optional)

The Perl documentation converstion utilities, required
for building the correspdonding program documentation
formats, should have come with your Perl.

=back



=head1 INSTALLATION

Issue the following commands to the shell:

 sh ./configure
 make
 make install

See the file INSTALL in the top-level distribution
directory for details.

=head1 BUILD FROM CVS

To build from CVS, you need the GNU utilities
aclocal, automake, autoconf, and libtool.  If
you have these, you can just run the top-level
script:

 sh ./autogen.sh

This will create the 'configure' script and other
necessary build files.


=head1 KNOWN BUGS

Probably many.

=begin comment text

This package is obsolete and deprecated.
Potential users are strongly encouraged to switch to
MorphConsole, available at ... ?

This will cease being a comment as soon as
MorphConsole has matured a bit.

=end comment text

=head1 ACKNOWLEDGEMENTS

Development of this package was supported by the project
'Kollokationen im Wörterbuch'
("collocations in the dictionary", http://www.bbaw.de/forschung/kollokationen )
in association with the project
'Digitales Wörterbuch der deutschen Sprache des 20. Jahrhunderts (DWDS)'
("digital dictionary of the German language of the 20th century", http://www.dwds.de )
at the Berlin-Brandenburgische Akademie der Wissenschaften ( http://www.bbaw.de )
with funding from
the Alexander von Humboldt Stiftung ( http://www.avh.de )
and from the Zukunftsinvestitionsprogramm of the
German federal government.

I am grateful to Christiane Fellbaum, Alexander Geyken,
Thomas Hanneforth, Gerald Neumann, Edmund Pohl, Alexey Sokirko,
and others for offering useful insights in the course of development
of this package.

Thomas Hanneforth wrote and maintains the libFSM C++ library
for finite-state device operations used in the development
of this package.

Alexander Geyken and Thomas Hanneforth developed the
rule-based morphological analysis system for German
which was used in the development and testing of this package.

=head1 AUTHOR

Bryan Jurish E<lt>moocow@ling.uni-potsdam.deE<gt>

=cut
